baseURL = "https://northmatrix.github.io"
languageCode = "en-us"
title = "Jamie Grant"
theme = "aurora"

[markup]
  [markup.highlight]
    style = "onedark"
    noClasses = false
    lineNos = true
    lineNumbersInTable = false
    tabWidth = 2

[params]
  author = "Jamie Grant"
  description = "I like maths & hacking."
  avatar = "/img/avatar.png"

  [[params.links]]
    name  = "GitHub"
    url   = "https://github.com/northmatrix"
    icon  = "github"

  [[params.links]]
    name  = "TryHackMe"
    url   = "https://tryhackme.com/p/Northmatrix"
    icon  = "tryhackme"

  [[params.links]]
    name  = "CryptoHack"
    url   = "https://cryptohack.org/user/northmatrix"
    icon  = "cryptohack"

  [[params.links]]
    name  = "pwn.college"
    url   = "https://pwn.college/hacker/127307"
    icon  = "pwncollege"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
